#!/usr/bin/env php
<?php
require_once dirname(__FILE__) . '/boot_console.php';
use zing\Console as C;

array_shift($_SERVER['argv']);

$action		= empty($_SERVER['argv']) ? 'list' : array_shift($_SERVER['argv']);
$manager	= zing\generator\Manager::instance();

switch ($action) {
	
	case 'list':
	
		$table = new \zing\console\Table;
		$table->add_header('Generator');
		$table->add_header('Description');
		
		foreach ($manager->generators() as $generator) {
			$table->add_row(array($generator->name(),
								  $generator->description()));
		}
		
		C::write($table);
		
		break;
		
	default:
	
		try {
			
			$generator_name		= $action;
			$generator_args		= phake\Utils::parse_args($_SERVER['argv']);
			$generator			= $manager->get_generator($generator_name);
			
			$generator->invoke($generator_args);
			
		} catch (zing\generator\GeneratorNotFoundException $gnfe) {
			C::error("Error: generator '$generator_name' not found");
			exit(1);
		} catch (Exception $e) {
			C::exception($e);
			exit(1);
		}
	
		break;
	
}
?>