#!/usr/bin/env php
<?php
require_once dirname(__FILE__) . '/boot_console.php';

use zing\Console as C;

try {
	
	$adapter_name	= $_ZING['zing.server']['adapter'];
	$adapter_class 	= \zing\server\adapters\AbstractAdapter::for_name($adapter_name);
	$adapter		= new $adapter_class;
	
	// TODO: port from command line
	if (isset($_ZING['zing.server']['port'])) {
		$adapter->set_port($_ZING['zing.server']['port']);
	}
	
	C::write("Starting {$adapter->get_server_string()} on port {$adapter->get_port()}");
	
	$adapter->start();

} catch (\zing\server\adapters\UnknownAdapterException $uae) {
	C::error("Unknown server adapter: $adapter_name");
	exit(1);
} catch (\Exception $e) {
	C::error("Error: " . get_class($e));
	C::error($e->getMessage());
	exit(1);
}
?>