#!/usr/bin/env php
<?php
require_once dirname(__FILE__) . '/boot_console.php';

$adapter_class = $_ZING['zing.server']['adapter'];

try {
	
	$adapter = new $adapter_class;
	
	// TODO: port from command line
	if (isset($_ZING['zing.server']['port'])) {
		$adapter->set_port($_ZING['zing.server']['port']);
	}
	
	fwrite(STDOUT, "Starting {$adapter->get_server_string()} on port {$adapter->get_port()}\n");
	
	$adapter->start();

} catch (\Exception $e) {
	fwrite(STDERR, "Error: " . get_class($e) . "\n");
	fwrite(STDERR, $e->getMessage() . "\n");
	exit(1);
}
?>