<?php
//
// Customise this stuff

if (isset($_SERVER['ZING_ENV'])) {
    define('ZING_ENV', $_SERVER['ZING_ENV']);
} else {
    define('ZING_ENV', 'development');
}

date_default_timezone_set('Europe/London');

//
// End customisable bits

define('ZING_CONFIG_DIR',   dirname(__FILE__));
define('ZING_ENV_DIR',      ZING_CONFIG_DIR . '/environments');
define('ZING_ROOT',         dirname(ZING_CONFIG_DIR));

set_include_path('.:' . ZING_ROOT);

load_environment('main');

//
// Essentials!

function load_environment($name) {
    require ZING_ENV_DIR . '/' . ZING_ENV . '/' . $name . '.php';
}

function read_environment($name) {
    $ENV = array();
    require ZING_ENV_DIR . '/' . ZING_ENV . '/' . $name . '.php';
    return $ENV;
}

// set_exception_handler("pym_exception_handler");
// function pym_exception_handler($e) {
//  if (DEBUG) {
//      display_template(":exception_handler", array('exception' => $e));
//  } else {
//      echo "Application Error";
//      log_exception($e);
//  }
// }

//
// Bail out if we're running from the console

if (php_sapi_name() == 'cli') {
    echo "Console initialised, environment: " . ZING_ENV . "\n";
    return;
}

//
// Everything under here is web-only...

set_exception_handler('my_exception_handler');

//
// The autoloader is auto-generated by the 'core:regenerate_autoload_map' task
// (or you can use 'core:kick', which updates all cached stuff)

function __autoload($class) {

    // SUPERLOAD-BEGIN
	static $map = array (
	  'RecordNotFoundException' => 'vendor/spitfire/runtime/spitfire.php',
	  'RecordInvalidException' => 'vendor/spitfire/runtime/spitfire.php',
	  'Errors' => 'vendor/spitfire/runtime/spitfire.php',
	  'SpitfireModel' => 'vendor/spitfire/runtime/spitfire.php',
	  'IllegalArgumentException' => 'vendor/base-php/inc/base.php',
	  'IllegalStateException' => 'vendor/base-php/inc/base.php',
	  'IOException' => 'vendor/base-php/inc/base.php',
	  'NotFoundException' => 'vendor/base-php/inc/base.php',
	  'SecurityException' => 'vendor/base-php/inc/base.php',
	  'SyntaxException' => 'vendor/base-php/inc/base.php',
	  'UnsupportedOperationException' => 'vendor/base-php/inc/base.php',
	  'Base' => 'vendor/base-php/inc/base.php',
	  'Callback' => 'vendor/base-php/inc/base.php',
	  'FunctionCallback' => 'vendor/base-php/inc/base.php',
	  'InstanceCallback' => 'vendor/base-php/inc/base.php',
	  'StaticCallback' => 'vendor/base-php/inc/base.php',
	  'Inflector' => 'vendor/base-php/inc/base.php',
	  'Date' => 'vendor/base-php/inc/date.php',
	  'Date_Time' => 'vendor/base-php/inc/date.php',
	  'File' => 'vendor/base-php/inc/file.php',
	  'UploadedFile' => 'vendor/base-php/inc/file.php',
	  'UploadedFileError' => 'vendor/base-php/inc/file.php',
	  'MIME' => 'vendor/base-php/inc/mime.php',
	  'MoneyConversionException' => 'vendor/base-php/inc/money.php',
	  'Money' => 'vendor/base-php/inc/money.php',
	  'MoneyBank' => 'vendor/base-php/inc/money.php',
	  'ISO_Country' => 'vendor/base-php/inc/iso/country.php',
	  'ISO_Language' => 'vendor/base-php/inc/iso/language.php',
	  'GDBException' => 'vendor/base-php/inc/gdb/gdb.php',
	  'GDBQueryException' => 'vendor/base-php/inc/gdb/gdb.php',
	  'GDBIntegrityConstraintViolation' => 'vendor/base-php/inc/gdb/gdb.php',
	  'GDBForeignKeyViolation' => 'vendor/base-php/inc/gdb/gdb.php',
	  'GDBUniqueViolation' => 'vendor/base-php/inc/gdb/gdb.php',
	  'GDBCheckViolation' => 'vendor/base-php/inc/gdb/gdb.php',
	  'GDB' => 'vendor/base-php/inc/gdb/gdb.php',
	  'GDBMySQL' => 'vendor/base-php/inc/gdb/gdb.php',
	  'GDBResult' => 'vendor/base-php/inc/gdb/gdb.php',
	  'GDBResultMySQL' => 'vendor/base-php/inc/gdb/gdb.php',
	  'gdb\\Migration' => 'vendor/base-php/inc/gdb/migration.php',
	  'gdb\\SchemaBuilder' => 'vendor/base-php/inc/gdb/schema_builder.php',
	  'gdb\\TableDefinition' => 'vendor/base-php/inc/gdb/table_definition.php',
	  'AbstractListing' => 'app/models/AbstractListing.php',
	  'Area' => 'app/models/Area.php',
	  'AuctionWatch' => 'app/models/AuctionWatch.php',
	  'Bid' => 'app/models/Bid.php',
	  'Bidder' => 'app/models/Bidder.php',
	  'Business' => 'app/models/Business.php',
	  'BusinessSearch' => 'app/models/BusinessSearch.php',
	  'Buyer' => 'app/models/Buyer.php',
	  'DownloadableMenu' => 'app/models/DownloadableMenu.php',
	  'ListingResult' => 'app/models/ListingResult.php',
	  'ListingSearch' => 'app/models/ListingSearch.php',
	  'ListingVoucherAdapter' => 'app/models/ListingVoucherAdapter.php',
	  'ListingVoucher' => 'app/models/PDFVoucher.php',
	  'TestModel' => 'app/models/TestModel.php',
	  'User' => 'app/models/User.php',
	  'UserActivity' => 'app/models/UserActivity.php',
	  'GeoData' => 'app/engine/GeoData.php',
	  'Mailer' => 'app/engine/Mailer.php',
	  'UserSession' => 'app/engine/UserSession.php',
	  'WorkQueue' => 'app/engine/WorkQueue.php',
	);
	// SUPERLOAD-END
    
    if (isset($map[$class])) {
        require $map[$class];
    }
    
}
?>